stages:
  - build
  - test
  - sonar
  - deploy

variables:
  NODE_IMAGE: 'node:20'
  DOCKER_IMAGE_NAME: '$DOCKERHUB_USERNAME/$CONTAINER_NAME'
  PRODUCTION_TAG: 'latest'
  STAGING_TAG: 'staging'
  TAG: ''
  GCP_HOST: ''
  ENV: ''

build:
  stage: build
  image: $NODE_IMAGE
  before_script:
    - yarn
  script:
    - yarn build
  artifacts:
    paths:
      - dist/

test:
  stage: test
  image: $NODE_IMAGE
  before_script:
    - yarn
  script:
    - export DATABASE_URL=$TEST_DATABASE_URL
    - yarn migrate
    - yarn test:ci
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
  dependencies:
    - build
  artifacts:
    paths:
      - coverage/

sonar:
  stage: sonar
  image: $NODE_IMAGE
  before_script:
    - yarn
  script:
    - yarn sonar-scanner -Dsonar.host.url=$SONAR_HOST -Dsonar.login=$SONAR_LOGIN -Dsonar.projectKey=$SONAR_PROJECT_KEY -Dsonar.projectName=tracer-study-be -Dsonar.sources=src -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info -Dsonar.exclusions=src/main.ts,**/*.spec.ts
  dependencies:
    - test
  only:
    - staging

publish:
  stage: deploy
  dependencies:
    - test
  before_script:
    - |
      if [ "$CI_COMMIT_BRANCH" == "main" ]; then
        export TAG=$PRODUCTION_TAG
      elif [ "$CI_COMMIT_BRANCH" == "staging" ]; then
        export TAG=$STAGING_TAG
      fi
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
  script:
    - docker build -t $DOCKER_IMAGE_NAME:$TAG .
    - docker push $DOCKER_IMAGE_NAME:$TAG
  only:
    - main
    - staging
  tags:
    - shell

deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - |
      if [ "$CI_COMMIT_BRANCH" == "main" ]; then
        export TAG=$PRODUCTION_TAG
        export GCP_HOST=$PRODUCTION_GCP_HOST
        export ENV=$ENV_PRODUCTION
      elif [ "$CI_COMMIT_BRANCH" == "staging" ]; then
        export TAG=$STAGING_TAG
        export GCP_HOST=$STAGING_GCP_HOST
        export ENV=$ENV_STAGING
      fi
    - chmod 400 $SSH_KEY
    - apk update && apk add openssh-client
  script:
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY $GCP_USERNAME@$GCP_HOST "
      printf \"%s\" \"$ENV\" > .env || true &&
      docker container rm -f $CONTAINER_NAME || true &&
      docker image rm -f $DOCKER_IMAGE_NAME:$TAG || true &&
      docker run --name $CONTAINER_NAME --env-file=.env -v $HOST_KEY_LOCATION:$DOCKER_KEY_LOCATION -v $HOST_CERT_LOCATION:$DOCKER_CERT_LOCATION -d -p 443:443 $DOCKER_IMAGE_NAME:$TAG"
  only:
    - main
    - staging
  needs:
    - job: publish
  tags:
    - ssh
