stages:
  - build
  - test

variables:
  NODE_IMAGE: 'node:20'

before_script:
  - yarn

build:
  stage: build
  image: $NODE_IMAGE
  script:
    - yarn build
  artifacts:
    paths:
      - dist/

test:
  stage: test
  image: $NODE_IMAGE
  script:
    - DATABASE_URL=$TEST_DATABASE_URL yarn test:ci
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
  dependencies:
    - build
